#%RAML 1.0 Trait
  usage: Apply this trait to enforce client_id identification.
  headers: 
      client_id:
        type: string
        description: Client secret to authenticate to system API
        required: true
      client_secret:
        type: string
        required: true
        description: Client secret to authenticate to system API