#%RAML 1.0
title: who-sapi
version: v1
baseUri: http://{environment}/covid/{version}/
baseUriParameters:
  environment:
    description: DEV, TEST, UAT, PROD
    enum: ["uho-dev-who-sapi.us-e2.cloudhub.io","uho-test-who-sapi.us-e2.cloudhub.io", "uho-uat-who-sapi.us-e2.cloudhub.io", "uho-prod-who-sapi.us-e2.cloudhub.io"]
traits:
  client-id-header: !include exchange_modules/d896f4a8-62ed-4bab-9db4-5db7ac45ebd4/client-id-required/1.0.0/client-id-required.raml
  transaction-header: !include exchange_modules/d896f4a8-62ed-4bab-9db4-5db7ac45ebd4/transaction-header/1.0.0/transaction-header.raml
  correlation-id-header: !include exchange_modules/d896f4a8-62ed-4bab-9db4-5db7ac45ebd4/correlation-id-header/1.0.0/correlation-id-header.raml
uses:
  resource-types: exchange_modules/d896f4a8-62ed-4bab-9db4-5db7ac45ebd4/resource-types/1.0.0/resource-types.raml
  common-data-types: exchange_modules/d896f4a8-62ed-4bab-9db4-5db7ac45ebd4/common-data-types/1.0.0/common-data-types.raml
  who-sapi-types: who-sapi-types/who-sapi-types.raml
/case:
  post:
    description: To register covid case
    is: [client-id-header,correlation-id-header,transaction-header]
    body:
      application/json:
        type: who-sapi-types.report-covid-case-request-type
        example: !include examples/report-covid-case-request.json
    responses:
      200:
        body:
          application/json:
            type: who-sapi-types.report-covid-case-response-type
            example: !include examples/report-covid-case-response.json
      400:
        body:
          application/json:
            type: common-data-types.errorType
            example: !include examples/400.json
      503:
        body:
          application/json:
            type: common-data-types.errorType
            example: !include examples/503.json
      500:
        body:
          application/json:
            type: common-data-types.errorType
            example: !include examples/500.json
/health-check:
  get:
  type:
    resource-types.all: 
      getResponseType: string